# Generated by Django 4.2.4 on 2023-09-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='appointment',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Продолжительность'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Проверено'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(verbose_name='Конец работы'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.TimeField(verbose_name='Начало работы'),
        ),
    ]
